CREATE TABLE IF NOT EXISTS b_my_price_watch (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UF_PRODUCT_URL VARCHAR(512) NOT NULL,
    UF_PRICE DECIMAL(10,2) NOT NULL DEFAULT 0,
    UF_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    UF_DATE_CREATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
